# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebom_name', models.CharField(max_length=200)),
                ('date_of_addition', models.DateTimeField(verbose_name='date published')),
                ('manager_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('date_of_addition', models.DateTimeField(verbose_name='date published')),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=200)),
                ('ebom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Ebom')),
            ],
        ),
    ]
