# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181115_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_details_wrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapper_name', models.CharField(max_length=200)),
                ('date_of_addition', models.DateTimeField(verbose_name='date published')),
                ('manager_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='additional_product_that_are_added',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('date_of_addition', models.DateTimeField(verbose_name='date published')),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=200)),
                ('supply_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Additional_details_wrapper')),
            ],
        ),
        migrations.AlterField(
            model_name='mbom',
            name='additionalDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Product'),
        ),
    ]
