# Generated by Django 2.1.3 on 2018-11-16 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20181115_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbom',
            name='additionalDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Product'),
        ),
    ]
